### ISSUE TITLE
Why is it 255?

### ISSUE THREAD

**Issue by gatoo** [Andrtisar/cppStuff#3]
https://github.com/Andrtisar/cppStuff/blob/3aaab28634ddd7ce1f2a9f8525db21a2bd21f242/Test/Test/Source.cpp#L30

**Comment by Andrtisar** [comment]
I don't really know what force of nature guided me towards 255, as ASCII only has chars from 0 to 127. Fixed that, and also control chars are excluded now, leading to an array of length 95
